name: Build and Deploy Advent Calendar

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Create JAR file
        run: |
          mkdir -p build/jar
          cp build/libs/*.jar build/jar/advent-calendar.jar

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v2
        with:
          name: advent-calendar-jar
          path: build/jar/advent-calendar.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download JAR artifact
        uses: actions/download-artifact@v2
        with:
          name: advent-calendar-jar
          path: public/downloads

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
